In [1]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6), (7,8,9), (10,11,12)])
e.ravel()[0]=2
np.nonzero(e==2)

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))

In [2]:
x=1

x++

print(x)

SyntaxError: invalid syntax (<ipython-input-2-edb6ef8c582d>, line 3)

In [13]:
name1=["kunal","lokeah","garv","danish"]
name2=name1[:]
name3=name1[:]

name2[0]="arjun"
name3[1]="bhavesh"

sum=0

for ls in (name1,name2,name3):
    if ls[0]=="arjun":
        sum+=4
    if ls[1]=="bhavesh":
        sum+=10
        
print(sum)

14


In [10]:
name1,name2

(['arjun', 'lokeah', 'garv', 'danish'], ['arjun', 'lokeah', 'garv', 'danish'])

In [12]:
x=[0,1,2,3]
y=x
x[0]=5
print(x,y)

[5, 1, 2, 3] [5, 1, 2, 3]


In [7]:
x

'happy'

In [8]:
y

'hap'

In [14]:
my_tuple = ((1, 2),) * 7

print(len(my_tuple[3:8]))

4


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]]) + 100

a = np.array([[1, 2, 3], [4, 5, 6]]) + [100]

In [16]:
a

array([[101, 102, 103],
       [104, 105, 106]])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]]) + [100]

In [18]:
a

array([[101, 102, 103],
       [104, 105, 106]])

In [19]:
my_tuple

((1, 2), (1, 2), (1, 2), (1, 2), (1, 2), (1, 2), (1, 2))

In [20]:
dict([[1,'A'],[2,'B']])

{1: 'A', 2: 'B'}

In [22]:
a=np.array([72.2, 31.9, 26.5, 29.1, 27.3, 8.6, 22.3, 26.5, 20.4, 12.8, 25.1, 19.2, 24.1, 58.2, 68.1, 89.2, 55.1, 9.4, 14.5, 13.9, 20.7, 17.9, 8.5, 55])

In [24]:
np.mean(a)

31.520833333333332