In [1]:
import pandas as pd
import numpy as np

In [2]:
file1=r"C:\Users\swadhin biswal\Desktop\happy data scientist\online projects\train.csv"
file2=r"C:\Users\swadhin biswal\Desktop\happy data scientist\online projects\test.csv"

In [3]:
train=pd.read_csv(file1)
test=pd.read_csv(file2)

In [4]:
train.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers ...   m4  m5 m6  m7  m8  m9  m10  m11  \
0             95                  1.0 ...    0   0  0   1   0   0    0    0   
1             72                  1.0 ...    0   0  0   0   0   0    0    1   
2             49                  1.0 ...    0   0  0   0   0   0    0    0   
3             46                  2.0 ...    0   0  0   0   0   1    1    1   
4             80                  1.0 ...    3   4  5   6   7   8    9   10   

   m12  m13  
0    0    1  
1    0    1  
2    0    1  
3    1    1  
4   11    1  

[5 rows x 29 columns]

In [5]:
train.dtypes

loan_id                       int64
source                       object
financial_institution        object
interest_rate               float64
unpaid_principal_bal          int64
loan_term                     int64
origination_date             object
first_payment_date           object
loan_to_value                 int64
number_of_borrowers         float64
debt_to_income_ratio        float64
borrower_credit_score       float64
loan_purpose                 object
insurance_percent           float64
co-borrower_credit_score    float64
insurance_type              float64
m1                            int64
m2                            int64
m3                            int64
m4                            int64
m5                            int64
m6                            int64
m7                            int64
m8                            int64
m9                            int64
m10                           int64
m11                           int64
m12                         

In [6]:
test["data"]="test"
test["m13"]=np.nan
train["data"]="train"

In [7]:
ld=pd.concat([train,test],axis=0)

C:\Users\swadhin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [8]:
ld.shape

(151924, 30)

In [9]:
train.shape

(116058, 30)

In [10]:
train.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers  ...    m5  m6 m7  m8  m9  m10  m11  \
0             95                  1.0  ...     0   0  1   0   0    0    0   
1             72                  1.0  ...     0   0  0   0   0    0    1   
2             49                  1.0  ...     0   0  0   0   0    0    0   
3             46                  2.0  ...     0   0  0   0   1    1    1   
4             80                  1.0  ...     4   5  6   7   8    9   10   

   m12  m13   data  
0    0    1  train  
1    0    1  train  
2    0    1  train  
3    1    1  train  
4   11    1  train  

[5 rows x 30 columns]

In [11]:
ld["loan_purpose"].value_counts()

A23    76354
B12    38580
C86    36990
Name: loan_purpose, dtype: int64

In [12]:
ld.dtypes

borrower_credit_score       float64
co-borrower_credit_score    float64
data                         object
debt_to_income_ratio        float64
financial_institution        object
first_payment_date           object
insurance_percent           float64
insurance_type              float64
interest_rate               float64
loan_id                       int64
loan_purpose                 object
loan_term                     int64
loan_to_value                 int64
m1                            int64
m10                           int64
m11                           int64
m12                           int64
m13                         float64
m2                            int64
m3                            int64
m4                            int64
m5                            int64
m6                            int64
m7                            int64
m8                            int64
m9                            int64
number_of_borrowers         float64
origination_date            

In [13]:
ld["m13"].value_counts()

0.0    115422
1.0       636
Name: m13, dtype: int64

In [14]:
ld.isnull().sum()

borrower_credit_score           0
co-borrower_credit_score        0
data                            0
debt_to_income_ratio            0
financial_institution           0
first_payment_date              0
insurance_percent               0
insurance_type                  0
interest_rate                   0
loan_id                         0
loan_purpose                    0
loan_term                       0
loan_to_value                   0
m1                              0
m10                             0
m11                             0
m12                             0
m13                         35866
m2                              0
m3                              0
m4                              0
m5                              0
m6                              0
m7                              0
m8                              0
m9                              0
number_of_borrowers             0
origination_date                0
source                          0
unpaid_princip

In [15]:
ld.select_dtypes(["object"]).columns

Index(['data', 'financial_institution', 'first_payment_date', 'loan_purpose',
       'origination_date', 'source'],
      dtype='object')

In [16]:
ld.drop(["first_payment_date","origination_date"],axis=1,inplace=True)

In [17]:
ld.shape

(151924, 28)

In [18]:
cols=ld.select_dtypes(["object"]).columns

In [19]:
cols=['financial_institution', 'loan_purpose', 'source']

In [20]:
for col in cols:
    k=ld[col].value_counts()
    k=k.index[:-1]
    for i in k:
        name=col +i
        ld[name]=np.where(ld[col]==i,1,0)
    del ld[col]
    
    

In [21]:
ld.shape

(151924, 47)

In [22]:
ld.head()

borrower_credit_score  co-borrower_credit_score   data  \
0                  694.0                       0.0  train   
1                  697.0                       0.0  train   
2                  780.0                       0.0  train   
3                  633.0                     638.0  train   
4                  681.0                       0.0  train   

   debt_to_income_ratio  insurance_percent  insurance_type  interest_rate  \
0                  22.0               30.0             0.0          4.250   
1                  44.0                0.0             0.0          4.875   
2                  33.0                0.0             0.0          3.250   
3                  44.0                0.0             0.0          4.750   
4                  43.0                0.0             0.0          4.750   

        loan_id  loan_term  loan_to_value   ...     \
0  268055008619        360             95   ...      
1  672831657627        360             72   ...      
2  742515242108        180             49   ...      
3  601385667462        360             46   ...      
4  273870029961        360             80   ...      

   financial_institutionSanchez-Robinson  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   financial_institutionSanchez, Hays and Wilkerson  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 0   
4                                                 0   

   financial_institutionRomero, Woods and Johnson  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   financial_institutionThornton-Davis  financial_institutionRichardson Ltd  \
0                                    0                                    0   
1                                    0                                    0   
2                                    1                                    0   
3                                    0                                    0   
4                                    0                                    0   

   financial_institutionAnderson-Taylor  loan_purposeA23  loan_purposeB12  \
0                                     0                0                0   
1                                     0                0                1   
2                                     0                0                1   
3                                     0                0                1   
4                                     0                0                0   

   sourceX  sourceY  
0        0        0  
1        0        1  
2        0        0  
3        1        0  
4        1        0  

[5 rows x 47 columns]

In [23]:
ld.select_dtypes(["object"]).columns

Index(['data'], dtype='object')

In [24]:
ld_train=ld.loc[ld["data"]=="train",]
ld_test=ld.loc[ld['data']=="test",]

In [25]:
ld_train.shape


(116058, 47)

In [26]:
ld_test.shape

(35866, 47)

In [27]:
del ld_train["data"]


In [28]:
ld_test.drop(["data","m13"],axis=1,inplace=True)

C:\Users\swadhin\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [29]:
ld_test.shape

(35866, 45)

In [30]:
ld_train.shape

(116058, 46)

In [31]:
from sklearn.model_selection import train_test_split,RandomizedSearchCV,GridSearchCV
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import roc_auc_score,confusion_matrix

In [32]:
ld_train_train,ld_train_val=train_test_split(ld_train,test_size=.25,random_state=2)

In [33]:
ld_train_train.shape

(87043, 46)

In [34]:
x_train_train=ld_train_train.drop(["m13"],axis=1)
y_train_train=ld_train_train["m13"]
x_train_val=ld_train_val.drop(["m13"],axis=1)
y_train_val=ld_train_val["m13"]


In [35]:
y_train_val.shape

(29015,)

In [42]:
lr=LogisticRegression(penalty="l1",C=1.5)
lr.fit(x_train_train,y_train_train)
p=lr.predict(x_train_val)
roc_auc_score(y_train_val,p)

C:\Users\swadhin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\swadhin\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.6595206456485717

In [120]:
p=lr.predict(x_train_val).


roc_auc_score(y_train_val,p)

0.6565967326184714

In [37]:
confusion_matrix(y_train_val,p,labels=[1,0])

array([[   57,   112],
       [   20, 28826]], dtype=int64)

In [38]:
tn=28826
tp=57
fp=20
fn=112
p=tp+fn
f=tn+fp
recall=tp/p
precision=tp/(tp+fp)
f_1=(2*precision*recall)/(precision+recall)

In [39]:
f_1

0.4634146341463415

In [47]:
cutoff=np.linspace(0.001,.999,999)

In [48]:
real=y_train_val
f_beta_list=[]
for c in cutoff:
    predicted=(p>c).astype(int)
    tp=((predicted==1) & (real==1)).sum()
    tn=((predicted==0) & (real==0)).sum()
    fp=((predicted==1) & (real==0)).sum()
    fn=((predicted==0) & (real==1)).sum()
    p=tp+fn
    f=tn+fp
    recall=tp/p
    precision=tp/(tp+fp)
    f_1=(2*precision*recall)/(precision+recall)
    f_beta_list.append(f_1)

In [50]:
max(f_beta_list)

0.01158168859649123

In [52]:
x_train=ld_train.drop(["m13"],axis=1)
y_train=ld_train["m13"]


In [53]:
lr=LogisticRegression(penalty="l1",C=2)
lr.fit(x_train,y_train)
p=lr.predict(ld_test)

C:\Users\swadhin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\swadhin\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [54]:
d=pd.DataFrame({"loan_id":test["loan_id"],"m13":p})


In [131]:
d["m13"].value_counts()

0.0    35770
1.0       96
Name: m13, dtype: int64

In [55]:
d.to_csv("test1.csv",index=False)

In [149]:
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [134]:
d_tree=DecisionTreeClassifier(class_weight="balanced")
d_tree.fit(x_train_train,y_train_train)
p=d_tree.predict(x_train_val)
roc_auc_score(y_train_val,p)

0.6755734492122419

In [135]:
confusion_matrix(y_train_val,p,labels=[1,0])

array([[   60,   109],
       [  112, 28734]], dtype=int64)

In [136]:
tn=28734
tp=60
fp=112
fn=109
p=tp+fn
f=tn+fp
recall=tp/p
precision=tp/(tp+fp)
f_1=(2*precision*recall)/(precision+recall)

In [139]:
p=d_tree.predict_proba(x_train_val)[:,1]

In [140]:
real=y_train_val
f_beta_list=[]
for c in cutoff:
    predicted=(p>c).astype(int)
    tp=((predicted==1) & (real==1)).sum()
    tn=((predicted==0) & (real==0)).sum()
    fp=((predicted==1) & (real==0)).sum()
    fn=((predicted==0) & (real==1)).sum()
    p=tp+fn
    f=tn+fp
    recall=tp/p
    precision=tp/(tp+fp)
    f_1=(2*precision*recall)/(precision+recall)
    f_beta_list.append(f_1)

In [141]:
max(f_beta_list)

0.3519061583577713

In [143]:
cutoff[f_beta_list==max(f_beta_list)]

TypeError: only integer scalar arrays can be converted to a scalar index

In [144]:
f_beta_list==max(f_beta_list)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [151]:
lr=DecisionTreeClassifier(class_weight="balanced")
lr.fit(x_train,y_train)
p=lr.predict_proba(ld_test)[:,1]

In [152]:
predicted=(p>0.1).astype(int)

In [153]:
d=pd.DataFrame({"loan_id":test["loan_id"],"m13":predicted})

In [154]:
d.to_csv("test1.csv",index=False)

In [150]:
rf=RandomForestClassifier()
params={"n_estimators":[50,100,200,300,500],
       "class_weight":["balanced",None],
       "criterion":["gini","entropy"],
       "bootstrap":[True,False],
       "max_depth":[20,25,30,40,50],
       "min_samples_split":[2,3,4,5,6],
       "min_samples_leaf":[1,2,3,4,5],
       "max_features":[10,15,20,30,15]}

In [151]:
rf_rv=RandomizedSearchCV(rf,param_distributions=params,cv=5,n_iter=100,scoring="roc_auc",verbose=1)
rf_rv.fit(x_train_train,y_train_train)


Fitting 5 folds for each of 100 candidates, totalling 500 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 500 out of 500 | elapsed: 2190.6min finished


0.6711989643431944

In [156]:
p=rf_rv.predict(x_train_val)
roc_auc_score(y_train_val,p)

0.6711989643431944

In [158]:
rf_rv.best_estimator_

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=20, max_features=10, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=6,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [159]:
confusion_matrix(y_train_val,p,labels=[1,0])

array([[   58,   111],
       [   23, 28823]], dtype=int64)

In [160]:


tn=28823
tp=58
fp=23
fn=111
p=tp+fn
f=tn+fp
recall=tp/p
precision=tp/(tp+fp)
f_1=(2*precision*recall)/(precision+recall)

In [161]:
f_1

0.4639999999999999

In [162]:
p=rf_rv.predict_proba(x_train_val)[:,1]

In [170]:
p.shape

(29015,)

In [163]:

cutoff=np.linspace(.01,.99,99)
real=y_train_val
f_beta_list=[]
for c in cutoff:
    predicted=(p>c).astype(int)
    tp=((predicted==1) & (real==1)).sum()
    tn=((predicted==0) & (real==0)).sum()
    fp=((predicted==1) & (real==0)).sum()
    fn=((predicted==0) & (real==1)).sum()
    p=tp+fn
    f=tn+fp
    recall=tp/p
    precision=tp/(tp+fp)
    f_1=(2*precision*recall)/(precision+recall)
    f_beta_list.append(f_1)

In [164]:
max(f_beta_list)

0.15210140093395597

In [56]:
from xgboost.sklearn import XGBClassifier

In [167]:
params={"n_estimators":[50,80,100,150,20],
       "max_depth":[2,3,4,5,6],
       "subsample":[.6,.7,.8,.9,1],
       "colsample_bytree":[.6,.7,.8,.9,1],
       "colsample_bylevel":[.6,.7,.8,.9,1],
       "colsample_bynode":[.6,.7,.8,.9,1],
       "learning_rate":[.01,.05,.1,.15,.20]}

In [168]:
xg=XGBClassifier(objective="binary:logistic")

In [170]:
xg_rv=RandomizedSearchCV(xg,param_distributions=params,cv=3,scoring="roc_auc",n_iter=300,verbose=1)
xg_rv.fit(x_train_train,y_train_train)
p=xg_rv.predict(x_train_val)
roc_auc_score(y_train_val,p)

Fitting 3 folds for each of 300 candidates, totalling 900 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 900 out of 900 | elapsed: 326.4min finished


0.6712856314720858

In [127]:
params={"scale_pos_weight":[1,5,10,20,50,100,160]}
xg_rv=GridSearchCV(xg,param_grid=params,cv=5,scoring="roc_auc")


0.6889504436331353

In [144]:
xg.fit(x_train_train,y_train_train)
p=xg.predict(x_train_val)
roc_auc_score(y_train_val,p)

0.7385529645901702

In [172]:
xg_rv.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=0.8,
       colsample_bynode=0.6, colsample_bytree=0.6, gamma=0,
       learning_rate=0.05, max_delta_step=0, max_depth=4,
       min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
       nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=None, subsample=0.7, verbosity=1)

In [89]:
0.7677747614653944,0.0.6889157767815788

In [145]:
confusion_matrix(y_train_val,p,labels=[1,0])


array([[   81,    88],
       [   63, 28783]], dtype=int64)

In [142]:

tn=28777
tp=84
fp=69
fn=85
p=tp+fn
f=tn+fp
recall=tp/p
precision=tp/(tp+fp)
f_1=(2*precision*recall)/(precision+recall)
f_1

0.5217391304347826

In [146]:
xg=XGBClassifier(objective="binary:logistic",max_depth=5,reg_alpha=0.5,reg_lambda=0.2,scale_pos_weight=10,n_estimators=150)
xg.fit(x_train,y_train)
p=xg.predict(ld_test)

In [147]:
d=pd.DataFrame({"loan_id":test["loan_id"],"m13":p})
d.to_csv("test1.csv",index=False)

In [94]:
y_train_train.value_counts()

0.0    86576
1.0      467
Name: m13, dtype: int64

In [165]:
rf=RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=20, max_features=10, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=6,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
rf.fit(x_train,y_train)
p=rf.predict(ld_test)

In [166]:
d=pd.DataFrame({"loan_id":test["loan_id"],"m13":p})
d.to_csv("test1.csv",index=False)